# SPDX-License-Identifier: MIT
# Copyright 2025 Tom F. (https://github.com/tomtom215)

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gosec
    - prealloc
    - unconvert
    - unparam
    - misspell

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gosec:
    excludes:
      - G204  # We validate command args before exec
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
