# SPDX-License-Identifier: MIT
# Copyright 2025 Tom F. (https://github.com/tomtom215)

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 50%
        threshold: 5%

ignore:
  - "**/*_test.go"
